// Code generated by pigeon; DO NOT EDIT.

// Package 'parser' implements the basic parser for 'hof-lang'
// i.e. there is no ast or validation
package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/hofstadter-io/hof-lang/pkg/ast"
)

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	switch v.(type) {
	case []interface{}:
		return v.([]interface{})
	default:
		return []interface{}{v}
	}
}

var g = &grammar{
	rules: []*rule{
		{
			name: "HOF",
			pos:  position{line: 25, col: 1, offset: 398},
			expr: &actionExpr{
				pos: position{line: 25, col: 8, offset: 405},
				run: (*parser).callonHOF1,
				expr: &seqExpr{
					pos: position{line: 25, col: 8, offset: 405},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 25, col: 8, offset: 405},
							label: "defs",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 13, offset: 410},
								name: "Definitions",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 25, offset: 422},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Definitions",
			pos:  position{line: 33, col: 1, offset: 514},
			expr: &actionExpr{
				pos: position{line: 33, col: 16, offset: 529},
				run: (*parser).callonDefinitions1,
				expr: &seqExpr{
					pos: position{line: 33, col: 16, offset: 529},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 33, col: 16, offset: 529},
							label: "defs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 33, col: 21, offset: 534},
								expr: &ruleRefExpr{
									pos:  position{line: 33, col: 23, offset: 536},
									name: "Definition",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 37, offset: 550},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Definition",
			pos:  position{line: 45, col: 1, offset: 711},
			expr: &actionExpr{
				pos: position{line: 45, col: 15, offset: 725},
				run: (*parser).callonDefinition1,
				expr: &seqExpr{
					pos: position{line: 45, col: 15, offset: 725},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 45, col: 15, offset: 725},
							name: "__",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 18, offset: 728},
							name: "DEF",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 22, offset: 732},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 24, offset: 734},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 29, offset: 739},
								name: "ID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 32, offset: 742},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 34, offset: 744},
							label: "dsl",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 38, offset: 748},
								name: "DSL",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 42, offset: 752},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 44, offset: 754},
							label: "body",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 49, offset: 759},
								name: "DefnBody",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 58, offset: 768},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "DefnBody",
			pos:  position{line: 55, col: 1, offset: 902},
			expr: &actionExpr{
				pos: position{line: 55, col: 13, offset: 914},
				run: (*parser).callonDefnBody1,
				expr: &seqExpr{
					pos: position{line: 55, col: 13, offset: 914},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 55, col: 13, offset: 914},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 17, offset: 918},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 20, offset: 921},
							label: "defs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 55, col: 25, offset: 926},
								expr: &ruleRefExpr{
									pos:  position{line: 55, col: 27, offset: 928},
									name: "DefnField",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 40, offset: 941},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 55, col: 43, offset: 944},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 47, offset: 948},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "DefnField",
			pos:  position{line: 68, col: 1, offset: 1104},
			expr: &actionExpr{
				pos: position{line: 68, col: 14, offset: 1117},
				run: (*parser).callonDefnField1,
				expr: &seqExpr{
					pos: position{line: 68, col: 14, offset: 1117},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 68, col: 14, offset: 1117},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 17, offset: 1120},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 68, col: 23, offset: 1126},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 68, col: 23, offset: 1126},
										name: "TypeDecl",
									},
									&ruleRefExpr{
										pos:  position{line: 68, col: 34, offset: 1137},
										name: "Field",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 42, offset: 1145},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "TypeDecl",
			pos:  position{line: 72, col: 1, offset: 1173},
			expr: &actionExpr{
				pos: position{line: 72, col: 13, offset: 1185},
				run: (*parser).callonTypeDecl1,
				expr: &seqExpr{
					pos: position{line: 72, col: 13, offset: 1185},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 72, col: 13, offset: 1185},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 72, col: 15, offset: 1187},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 18, offset: 1190},
								name: "ID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 21, offset: 1193},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 72, col: 23, offset: 1195},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 27, offset: 1199},
								name: "TYPE",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 32, offset: 1204},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 72, col: 34, offset: 1206},
							label: "obj",
							expr: &zeroOrOneExpr{
								pos: position{line: 72, col: 38, offset: 1210},
								expr: &ruleRefExpr{
									pos:  position{line: 72, col: 38, offset: 1210},
									name: "Object",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 46, offset: 1218},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 85, col: 1, offset: 1390},
			expr: &actionExpr{
				pos: position{line: 85, col: 10, offset: 1399},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 85, col: 10, offset: 1399},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 85, col: 16, offset: 1405},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 85, col: 16, offset: 1405},
								name: "Boolean",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 26, offset: 1415},
								name: "TypeDecl",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 37, offset: 1426},
								name: "Object",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 46, offset: 1435},
								name: "Array",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 54, offset: 1443},
								name: "Number",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 63, offset: 1452},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 73, offset: 1462},
								name: "String",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 82, offset: 1471},
								name: "TypeRef",
							},
							&ruleRefExpr{
								pos:  position{line: 85, col: 92, offset: 1481},
								name: "Null",
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 89, col: 1, offset: 1513},
			expr: &actionExpr{
				pos: position{line: 89, col: 10, offset: 1522},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 89, col: 10, offset: 1522},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 89, col: 10, offset: 1522},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 89, col: 13, offset: 1525},
							label: "tok",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 17, offset: 1529},
								name: "Token",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 23, offset: 1535},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 89, col: 25, offset: 1537},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 29, offset: 1541},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 89, col: 31, offset: 1543},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 35, offset: 1547},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 41, offset: 1553},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 98, col: 1, offset: 1667},
			expr: &actionExpr{
				pos: position{line: 98, col: 11, offset: 1677},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 98, col: 11, offset: 1677},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 98, col: 11, offset: 1677},
							val:        "{",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 98, col: 15, offset: 1681},
							label: "fields",
							expr: &zeroOrMoreExpr{
								pos: position{line: 98, col: 22, offset: 1688},
								expr: &ruleRefExpr{
									pos:  position{line: 98, col: 24, offset: 1690},
									name: "Field",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 33, offset: 1699},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 98, col: 36, offset: 1702},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Elem",
			pos:  position{line: 109, col: 1, offset: 1920},
			expr: &actionExpr{
				pos: position{line: 109, col: 9, offset: 1928},
				run: (*parser).callonElem1,
				expr: &seqExpr{
					pos: position{line: 109, col: 9, offset: 1928},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 109, col: 9, offset: 1928},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 12, offset: 1931},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 16, offset: 1935},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 22, offset: 1941},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 109, col: 24, offset: 1943},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 28, offset: 1947},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 113, col: 1, offset: 1972},
			expr: &actionExpr{
				pos: position{line: 113, col: 10, offset: 1981},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 113, col: 10, offset: 1981},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 113, col: 10, offset: 1981},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 113, col: 14, offset: 1985},
							label: "elems",
							expr: &zeroOrMoreExpr{
								pos: position{line: 113, col: 20, offset: 1991},
								expr: &ruleRefExpr{
									pos:  position{line: 113, col: 22, offset: 1993},
									name: "Elem",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 113, col: 30, offset: 2001},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 113, col: 33, offset: 2004},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "CodeBlock",
			pos:  position{line: 122, col: 1, offset: 2225},
			expr: &actionExpr{
				pos: position{line: 122, col: 14, offset: 2238},
				run: (*parser).callonCodeBlock1,
				expr: &seqExpr{
					pos: position{line: 122, col: 14, offset: 2238},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 122, col: 14, offset: 2238},
							name: "Code",
						},
						&ruleRefExpr{
							pos:  position{line: 122, col: 19, offset: 2243},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Code",
			pos:  position{line: 127, col: 1, offset: 2293},
			expr: &zeroOrMoreExpr{
				pos: position{line: 127, col: 9, offset: 2301},
				expr: &choiceExpr{
					pos: position{line: 127, col: 11, offset: 2303},
					alternatives: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 127, col: 11, offset: 2303},
							expr: &seqExpr{
								pos: position{line: 127, col: 13, offset: 2305},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 127, col: 13, offset: 2305},
										expr: &charClassMatcher{
											pos:        position{line: 127, col: 14, offset: 2306},
											val:        "[{}]",
											chars:      []rune{'{', '}'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 127, col: 19, offset: 2311,
									},
								},
							},
						},
						&seqExpr{
							pos: position{line: 127, col: 26, offset: 2318},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 127, col: 26, offset: 2318},
									val:        "{",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 127, col: 30, offset: 2322},
									name: "Code",
								},
								&litMatcher{
									pos:        position{line: 127, col: 35, offset: 2327},
									val:        "}",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 129, col: 1, offset: 2335},
			expr: &actionExpr{
				pos: position{line: 129, col: 11, offset: 2345},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 129, col: 11, offset: 2345},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 129, col: 11, offset: 2345},
							expr: &litMatcher{
								pos:        position{line: 129, col: 11, offset: 2345},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 129, col: 16, offset: 2350},
							name: "Integer",
						},
						&litMatcher{
							pos:        position{line: 129, col: 24, offset: 2358},
							val:        ".",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 129, col: 28, offset: 2362},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 28, offset: 2362},
								name: "DecimalDigit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 42, offset: 2376},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 42, offset: 2376},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Index",
			pos:  position{line: 142, col: 1, offset: 2619},
			expr: &actionExpr{
				pos: position{line: 142, col: 10, offset: 2628},
				run: (*parser).callonIndex1,
				expr: &ruleRefExpr{
					pos:  position{line: 142, col: 10, offset: 2628},
					name: "Integer",
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 148, col: 1, offset: 2768},
			expr: &choiceExpr{
				pos: position{line: 148, col: 12, offset: 2779},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 148, col: 12, offset: 2779},
						val:        "0",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 148, col: 18, offset: 2785},
						run: (*parser).callonInteger3,
						expr: &seqExpr{
							pos: position{line: 148, col: 18, offset: 2785},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 148, col: 18, offset: 2785},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 148, col: 38, offset: 2805},
									expr: &ruleRefExpr{
										pos:  position{line: 148, col: 38, offset: 2805},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 161, col: 1, offset: 3047},
			expr: &seqExpr{
				pos: position{line: 161, col: 13, offset: 3059},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 161, col: 13, offset: 3059},
						val:        "e",
						ignoreCase: true,
					},
					&zeroOrOneExpr{
						pos: position{line: 161, col: 18, offset: 3064},
						expr: &charClassMatcher{
							pos:        position{line: 161, col: 18, offset: 3064},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 161, col: 24, offset: 3070},
						expr: &ruleRefExpr{
							pos:  position{line: 161, col: 24, offset: 3070},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 163, col: 1, offset: 3085},
			expr: &actionExpr{
				pos: position{line: 163, col: 11, offset: 3095},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 163, col: 11, offset: 3095},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 163, col: 11, offset: 3095},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 163, col: 15, offset: 3099},
							expr: &choiceExpr{
								pos: position{line: 163, col: 17, offset: 3101},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 163, col: 17, offset: 3101},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 163, col: 17, offset: 3101},
												expr: &ruleRefExpr{
													pos:  position{line: 163, col: 18, offset: 3102},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 163, col: 30, offset: 3114,
											},
										},
									},
									&seqExpr{
										pos: position{line: 163, col: 34, offset: 3118},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 163, col: 34, offset: 3118},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 163, col: 39, offset: 3123},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 163, col: 57, offset: 3141},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "AlphaNumeric",
			pos:  position{line: 177, col: 1, offset: 3448},
			expr: &choiceExpr{
				pos: position{line: 177, col: 17, offset: 3464},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 177, col: 17, offset: 3464},
						name: "Alphabetic",
					},
					&ruleRefExpr{
						pos:  position{line: 177, col: 30, offset: 3477},
						name: "DecimalDigit",
					},
				},
			},
		},
		{
			name: "Alphabetic",
			pos:  position{line: 179, col: 1, offset: 3491},
			expr: &charClassMatcher{
				pos:        position{line: 179, col: 15, offset: 3505},
				val:        "[a-zA-Z]",
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 181, col: 1, offset: 3515},
			expr: &charClassMatcher{
				pos:        position{line: 181, col: 16, offset: 3530},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 183, col: 1, offset: 3546},
			expr: &choiceExpr{
				pos: position{line: 183, col: 19, offset: 3564},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 183, col: 19, offset: 3564},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 183, col: 38, offset: 3583},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 185, col: 1, offset: 3598},
			expr: &charClassMatcher{
				pos:        position{line: 185, col: 21, offset: 3618},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 187, col: 1, offset: 3631},
			expr: &seqExpr{
				pos: position{line: 187, col: 18, offset: 3648},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 187, col: 18, offset: 3648},
						val:        "u",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 187, col: 22, offset: 3652},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 187, col: 31, offset: 3661},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 187, col: 40, offset: 3670},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 187, col: 49, offset: 3679},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 189, col: 1, offset: 3689},
			expr: &charClassMatcher{
				pos:        position{line: 189, col: 17, offset: 3705},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 191, col: 1, offset: 3712},
			expr: &charClassMatcher{
				pos:        position{line: 191, col: 24, offset: 3735},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 193, col: 1, offset: 3742},
			expr: &charClassMatcher{
				pos:        position{line: 193, col: 13, offset: 3754},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 195, col: 1, offset: 3765},
			expr: &choiceExpr{
				pos: position{line: 195, col: 12, offset: 3776},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 195, col: 12, offset: 3776},
						run: (*parser).callonBoolean2,
						expr: &litMatcher{
							pos:        position{line: 195, col: 12, offset: 3776},
							val:        "true",
							ignoreCase: false,
						},
					},
					&actionExpr{
						pos: position{line: 195, col: 62, offset: 3826},
						run: (*parser).callonBoolean4,
						expr: &litMatcher{
							pos:        position{line: 195, col: 62, offset: 3826},
							val:        "false",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 199, col: 1, offset: 3908},
			expr: &actionExpr{
				pos: position{line: 199, col: 9, offset: 3916},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 199, col: 9, offset: 3916},
					val:        "null",
					ignoreCase: false,
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 201, col: 1, offset: 3944},
			expr: &zeroOrMoreExpr{
				pos: position{line: 201, col: 6, offset: 3951},
				expr: &choiceExpr{
					pos: position{line: 201, col: 8, offset: 3953},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 201, col: 8, offset: 3953},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 201, col: 21, offset: 3966},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 201, col: 27, offset: 3972},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 202, col: 1, offset: 3983},
			expr: &zeroOrMoreExpr{
				pos: position{line: 202, col: 5, offset: 3989},
				expr: &choiceExpr{
					pos: position{line: 202, col: 7, offset: 3991},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 202, col: 7, offset: 3991},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 202, col: 20, offset: 4004},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 204, col: 1, offset: 4041},
			expr: &charClassMatcher{
				pos:        position{line: 204, col: 14, offset: 4056},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 205, col: 1, offset: 4064},
			expr: &litMatcher{
				pos:        position{line: 205, col: 7, offset: 4072},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOS",
			pos:  position{line: 206, col: 1, offset: 4077},
			expr: &choiceExpr{
				pos: position{line: 206, col: 7, offset: 4085},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 206, col: 7, offset: 4085},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 206, col: 7, offset: 4085},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 206, col: 10, offset: 4088},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
					&seqExpr{
						pos: position{line: 206, col: 16, offset: 4094},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 206, col: 16, offset: 4094},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 206, col: 18, offset: 4096},
								expr: &ruleRefExpr{
									pos:  position{line: 206, col: 18, offset: 4096},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 206, col: 37, offset: 4115},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 206, col: 43, offset: 4121},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 206, col: 43, offset: 4121},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 206, col: 46, offset: 4124},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 208, col: 1, offset: 4129},
			expr: &notExpr{
				pos: position{line: 208, col: 7, offset: 4137},
				expr: &anyMatcher{
					line: 208, col: 8, offset: 4138,
				},
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 211, col: 1, offset: 4142},
			expr: &anyMatcher{
				line: 211, col: 14, offset: 4157,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 212, col: 1, offset: 4159},
			expr: &choiceExpr{
				pos: position{line: 212, col: 11, offset: 4171},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 212, col: 11, offset: 4171},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 212, col: 30, offset: 4190},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 213, col: 1, offset: 4208},
			expr: &seqExpr{
				pos: position{line: 213, col: 20, offset: 4229},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 213, col: 20, offset: 4229},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 213, col: 25, offset: 4234},
						expr: &seqExpr{
							pos: position{line: 213, col: 27, offset: 4236},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 213, col: 27, offset: 4236},
									expr: &litMatcher{
										pos:        position{line: 213, col: 28, offset: 4237},
										val:        "*/",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 213, col: 33, offset: 4242},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 213, col: 47, offset: 4256},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 214, col: 1, offset: 4261},
			expr: &seqExpr{
				pos: position{line: 214, col: 36, offset: 4298},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 214, col: 36, offset: 4298},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 214, col: 41, offset: 4303},
						expr: &seqExpr{
							pos: position{line: 214, col: 43, offset: 4305},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 214, col: 43, offset: 4305},
									expr: &choiceExpr{
										pos: position{line: 214, col: 46, offset: 4308},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 214, col: 46, offset: 4308},
												val:        "*/",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 214, col: 53, offset: 4315},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 214, col: 59, offset: 4321},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 214, col: 73, offset: 4335},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 215, col: 1, offset: 4340},
			expr: &seqExpr{
				pos: position{line: 215, col: 21, offset: 4362},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 215, col: 21, offset: 4362},
						val:        "//",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 215, col: 26, offset: 4367},
						expr: &seqExpr{
							pos: position{line: 215, col: 28, offset: 4369},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 215, col: 28, offset: 4369},
									expr: &ruleRefExpr{
										pos:  position{line: 215, col: 29, offset: 4370},
										name: "EOL",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 215, col: 33, offset: 4374},
									name: "SourceChar",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DEF",
			pos:  position{line: 217, col: 1, offset: 4389},
			expr: &litMatcher{
				pos:        position{line: 217, col: 8, offset: 4396},
				val:        "def",
				ignoreCase: false,
			},
		},
		{
			name: "TypeRef",
			pos:  position{line: 219, col: 1, offset: 4403},
			expr: &actionExpr{
				pos: position{line: 219, col: 12, offset: 4414},
				run: (*parser).callonTypeRef1,
				expr: &labeledExpr{
					pos:   position{line: 219, col: 12, offset: 4414},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 219, col: 18, offset: 4420},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 219, col: 18, offset: 4420},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 219, col: 29, offset: 4431},
								expr: &choiceExpr{
									pos: position{line: 219, col: 31, offset: 4433},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 219, col: 31, offset: 4433},
											name: "TokenCharactors",
										},
										&charClassMatcher{
											pos:        position{line: 219, col: 49, offset: 4451},
											val:        "[.]",
											chars:      []rune{'.'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TYPE",
			pos:  position{line: 227, col: 1, offset: 4556},
			expr: &actionExpr{
				pos: position{line: 227, col: 9, offset: 4564},
				run: (*parser).callonTYPE1,
				expr: &labeledExpr{
					pos:   position{line: 227, col: 9, offset: 4564},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 227, col: 15, offset: 4570},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 227, col: 15, offset: 4570},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 227, col: 26, offset: 4581},
								expr: &ruleRefExpr{
									pos:  position{line: 227, col: 26, offset: 4581},
									name: "AlphaNumeric",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ID",
			pos:  position{line: 235, col: 1, offset: 4693},
			expr: &actionExpr{
				pos: position{line: 235, col: 7, offset: 4699},
				run: (*parser).callonID1,
				expr: &labeledExpr{
					pos:   position{line: 235, col: 7, offset: 4699},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 235, col: 13, offset: 4705},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 235, col: 13, offset: 4705},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 235, col: 24, offset: 4716},
								expr: &ruleRefExpr{
									pos:  position{line: 235, col: 24, offset: 4716},
									name: "AlphaNumeric",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DSL",
			pos:  position{line: 243, col: 1, offset: 4828},
			expr: &actionExpr{
				pos: position{line: 243, col: 8, offset: 4835},
				run: (*parser).callonDSL1,
				expr: &labeledExpr{
					pos:   position{line: 243, col: 8, offset: 4835},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 243, col: 14, offset: 4841},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 243, col: 14, offset: 4841},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 243, col: 25, offset: 4852},
								expr: &choiceExpr{
									pos: position{line: 243, col: 27, offset: 4854},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 243, col: 27, offset: 4854},
											name: "AlphaNumeric",
										},
										&charClassMatcher{
											pos:        position{line: 243, col: 42, offset: 4869},
											val:        "[/]",
											chars:      []rune{'/'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Token",
			pos:  position{line: 251, col: 1, offset: 4974},
			expr: &actionExpr{
				pos: position{line: 251, col: 10, offset: 4983},
				run: (*parser).callonToken1,
				expr: &labeledExpr{
					pos:   position{line: 251, col: 10, offset: 4983},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 251, col: 16, offset: 4989},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 251, col: 16, offset: 4989},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 251, col: 27, offset: 5000},
								expr: &ruleRefExpr{
									pos:  position{line: 251, col: 27, offset: 5000},
									name: "AlphaNumeric",
								},
							},
						},
					},
				},
			},
		},
	},
}

func (c *current) onHOF1(defs interface{}) (interface{}, error) {
	ret := ast.HofFile{
		Definitions: defs.([]ast.Definition),
	}

	return ret, nil
}

func (p *parser) callonHOF1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHOF1(stack["defs"])
}

func (c *current) onDefinitions1(defs interface{}) (interface{}, error) {

	ret := []ast.Definition{}
	vals := toIfaceSlice(defs)

	for _, def := range vals {
		ret = append(ret, def.(ast.Definition))
	}

	return ret, nil
}

func (p *parser) callonDefinitions1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinitions1(stack["defs"])
}

func (c *current) onDefinition1(name, dsl, body interface{}) (interface{}, error) {
	ret := ast.Definition{
		Name: name.(ast.Token),
		DSL:  dsl.(ast.Token),
		Body: body.([]ast.ASTNode),
	}

	return ret, nil
}

func (p *parser) callonDefinition1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinition1(stack["name"], stack["dsl"], stack["body"])
}

func (c *current) onDefnBody1(defs interface{}) (interface{}, error) {

	ret := []ast.ASTNode{}

	vals := toIfaceSlice(defs)

	for _, val := range vals {
		ret = append(ret, val.(ast.ASTNode))
	}

	return ret, nil
}

func (p *parser) callonDefnBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefnBody1(stack["defs"])
}

func (c *current) onDefnField1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonDefnField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefnField1(stack["val"])
}

func (c *current) onTypeDecl1(id, typ, obj interface{}) (interface{}, error) {
	ret := ast.TypeDecl{
		Name: id.(ast.Token),
		Type: typ.(ast.Token),
	}
	if obj != nil {
		objVal := obj.(ast.Object)
		ret.Extra = &objVal
	}

	return ret, nil
}

func (p *parser) callonTypeDecl1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeDecl1(stack["id"], stack["typ"], stack["obj"])
}

func (c *current) onValue1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onField1(tok, val interface{}) (interface{}, error) {
	ret := ast.Field{
		Key:   tok.(ast.Token),
		Value: val.(ast.ASTNode),
	}

	return ret, nil
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["tok"], stack["val"])
}

func (c *current) onObject1(fields interface{}) (interface{}, error) {
	vals := toIfaceSlice(fields)
	ret := ast.Object{Fields: make([]ast.Field, 0, len(vals))}

	for _, val := range vals {
		ret.Fields = append(ret.Fields, val.(ast.Field))
	}

	return ret, nil
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["fields"])
}

func (c *current) onElem1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonElem1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onElem1(stack["val"])
}

func (c *current) onArray1(elems interface{}) (interface{}, error) {
	vals := toIfaceSlice(elems)
	ret := ast.Array{Elems: make([]ast.ASTNode, 0, len(vals))}
	for _, val := range vals {
		ret.Elems = append(ret.Elems, val.(ast.ASTNode))
	}
	return ret, nil
}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["elems"])
}

func (c *current) onCodeBlock1() (interface{}, error) {
	text := string(c.text)
	return text, nil
}

func (p *parser) callonCodeBlock1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCodeBlock1()
}

func (c *current) onNumber1() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	val, err := strconv.ParseFloat(string(c.text), 64)
	if err != nil {
		return nil, err
	}

	ret := ast.Decimal{Value: val}

	return ret, nil
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onIndex1() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonIndex1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndex1()
}

func (c *current) onInteger3() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	val, err := strconv.ParseInt(string(c.text), 10, 64)
	if err != nil {
		return nil, err
	}

	ret := ast.Integer{Value: int(val)}

	return ret, nil
}

func (p *parser) callonInteger3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger3()
}

func (c *current) onString1() (interface{}, error) {
	// TODO : the forward slash (solidus) is not a valid escape in Go, it will
	// fail if there's one in the string
	text, err := strconv.Unquote(string(c.text))
	if err != nil {
		return ast.Token{}, err
	}

	ret := ast.Token{
		Value: text,
	}
	return ret, nil
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onBoolean2() (interface{}, error) {
	return ast.Bool{Value: true}, nil
}

func (p *parser) callonBoolean2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean2()
}

func (c *current) onBoolean4() (interface{}, error) {
	return ast.Bool{Value: false}, nil
}

func (p *parser) callonBoolean4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean4()
}

func (c *current) onNull1() (interface{}, error) {
	return nil, nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onTypeRef1(val interface{}) (interface{}, error) {
	text := string(c.text)
	ret := ast.Token{
		Value: text,
	}
	return ret, nil
}

func (p *parser) callonTypeRef1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeRef1(stack["val"])
}

func (c *current) onTYPE1(val interface{}) (interface{}, error) {
	text := string(c.text)
	ret := ast.Token{
		Value: text,
	}
	return ret, nil
}

func (p *parser) callonTYPE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTYPE1(stack["val"])
}

func (c *current) onID1(val interface{}) (interface{}, error) {
	text := string(c.text)
	ret := ast.Token{
		Value: text,
	}
	return ret, nil
}

func (p *parser) callonID1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onID1(stack["val"])
}

func (c *current) onDSL1(val interface{}) (interface{}, error) {
	text := string(c.text)
	ret := ast.Token{
		Value: text,
	}
	return ret, nil
}

func (p *parser) callonDSL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDSL1(stack["val"])
}

func (c *current) onToken1(val interface{}) (interface{}, error) {
	text := string(c.text)
	ret := ast.Token{
		Value: text,
	}
	return ret, nil
}

func (p *parser) callonToken1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onToken1(stack["val"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
